COLUMNS:
  fixed acidity: float64
  volatile acidity: float64
  citric acid: float64
  residual sugar: float64
  chlorides: float64
  free sulfur dioxide: float64
  total sulfur dioxide: float64
  density: float64
  pH: float64
  sulphates: float64
  alcohol: float64
  quality: int64
<<<<<<< HEAD
=======
  Id: int64
>>>>>>> 4286e3ba86f1203d9507d357bf8e4e074ec06820


TARGET_COLUMN:
  name: quality